name: Deploy via SFTP to Cloudways

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    name: SFTP Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Cloudways via SFTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.SERVER }}
          username: ${{ secrets.USER_NAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          local-dir: ./ # or 'dist/' if you're building before deploy
          server-dir: ${{ secrets.SFTP_TARGET }}
          dangerous-clean-slate: false
